apiVersion: apps/v1
kind: Deployment
metadata:
  name: game
spec:
  selector:
    matchLabels:
      app: game
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: game
    spec:
      containers:
      - image: davictor/2048-game:1.2.0
        name: game
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
        resources:
          requests:
            memory: "64Mi"
            cpu: "200m"
          limits:
            memory: "1024Mi"
            cpu: "400m"
      restartPolicy: Always