apiVersion: apps/v1
kind: Deployment
metadata:
  name: game
spec:
  selector:
    matchLabels:
      app: game
  replicas: 3
  template:
    metadata:
      labels:
        app: game
    spec:
      containers:
      - image: davictor/2048-game:1.1.0
        name: game
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "200m"
          limits:
            memory: "1024Mi"
            cpu: "400m"
      restartPolicy: Always